== Move is not a silver bullet, it has issues too

=== Not every type is movable (and/or copyable)

[source,cpp,tabsize=2]
----
class openfile {
		FILE* f;
	public:
		explicit openfile(const char* filename) : f(std::fopen(filename, "rw")){
			if(!f){throw std::runtime_error("unable to open file");}
		}
		~openfile(){fclose(f);}
		void write(const char* message);
		// copy suppressed
};
----

Where should `f` point if `openfile` has been moved from?
If the class wants to support move semantic, it has to change it's invariants.

=== Language complexity

It makes the language specification more complex.


=== Move is not always an optimisation

As a copy is a valid move implementation, moves are not necessarily cheaper than copies

=== Which advantages does move-semantic provide?

Performance

[%notitle]
=== temporaries and expiring values are cheap

[source,cpp,tabsize=2]
----
std::vector<std::string> create() {
	std::vector<std::string> coll;
	coll.reserve(3);
	// ...
	coll.push_back(s+s); // because of push_back(T&&) and std::string(std::string&&);
	coll.push_back(std::move(s)); // because of push_back(T&&) and std::string(std::string&&);
	return coll; // because of std::vector<T>(std::vector<T>&&) and std::string(std::string&&);
}
----

	* returning locals by value is cheap
	* temporaries (unnamed) are cheap
	* it is possible to "mark" manually a value as temporary

[%notitle]
=== Which advantages does move-semantic provide

Simpliciteness: it is possible to return uncopyable (but moveable) types from function without adding further indirections.

[source,cpp,tabsize=2]
----
struct type_with_costly_or_no_copy_constructor{ /* ... */};

// allocates unnecessarily (which is a costly operation) to avoid a potential copy
// should the caller check for nullptr?
// does it point to one or more elements?
// is the pointed content shared with someone else?
// is it an owning pointer?
// should the caller free it? If yes, how?
type_with_costly_or_no_copy_constructor* factory();

// no overhead, less documentation needed, no leaks by design
type_with_costly_or_no_copy_constructor factory();
----

[%notitle]
=== Which advantages does move-semantic provide

Correctness: before {cpp}11 it was not possible to implement something like `std::unique_ptr`.
It's {cpp}03 counterpart, `std::auto_ptr` has been declared as broken beyond repair.

It's copy constructor does not copy, so, for example, it's not safe to use with stl algorithms, containers and other functions.

[source,cpp,tabsize=2]
----
// suppose that all pointer are != nullptr
std::auto_ptr<int> v[N] = { /* ... */ };
std::sort(v, v + N,
  [](const std::auto_ptr<int>& lhs, const std::auto_ptr<int>& rhs){
      return *lhs < *rhs;
}); // might crash if sort makes an internal temporary copy
----

[%notitle]
=== Which advantages does move-semantic provide

Consistency: eases generic programming.
The containers and algorithm from the standard library do work correctly (TM) with `std::unique_ptr`, but do not with `std::auto_ptr`.
And they do not require any special or separate implementation.

////
[%notitle]
=== Which advantages does move-semantic provide

Perfomance improvement for Exception safety/code correctness.


=== Exception safety

	* No-throw guarantee: Operations are guaranteed to succeed and satisfy all requirements even in exceptional situations.
	* Strong exception safety (commit/rollback semantics): Operations can fail, but failed operations are guaranteed to have no side effects, leaving the original values intact.
	* Basic exception safety (no-leak guarantee): Partial execution of failed operations can result in side effects, but all invariants are preserved and there are no resource leaks. Any stored data will contain valid values.
	* No exception safety: No guarantees are made.

[%notitle]
=== Exception safety

All classes in the standard have at least a basic exception safety garantuee, some classes have even a no-throw guarantee.
(All classes should aim at least for the basic exception safety.)

`std::vector::push_back`, http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2011/n3242.pdf#section.23.2[for example], has a "strong exception garantuee" (https://en.cppreference.com/w/cpp/container/vector/push_back[cppreference] normally documents the exception garantees)

[source,cpp,tabsize=2]
----
struct T { /* */ };
void foo(std::vector<T>& ts, const T& t){
	ts.push_back(t);
}
----

[%notitle]
=== Exception safety

It is possible for `push_back`, to provide a strong exception garantuee, even if there is no space left in the buffer

	* allocate a new, bigger buffer
	* copy all values in the new buffer
	* destroy the old values/deallocate the old buffer

As destructor normally have the no-throw garantuee, if one of the first step fails (throws), `ts` is left unchanged.
Providing this strong garantuee, means a lot of potentially unnecessary works, especially if most of the time every step succeeds.

[%notitle]
=== Exception safety

With move semantic, supposing that the move constructor does not throw(!), it is possible to

	* allocate a new, bigger buffer
	* move all values in the new buffer
	* destroy the old values/deallocate the old buffer

Which is generally faster than temporarely copying the whole vector.

[%notitle]
=== Exception safety

If a move constructor/assingment operator throws, then it is not possible to restore the old values, as 

	* the status of the moved value that throwed is unknown
	* even supposing that the value is unchanged, moving the values back to the old buffer might cause another move constructor to fail

Therefore if the move operator is not `noexcept` (ie: it does provide the no-throw garantuee), then `std::vector` will copy the values in order to provide the strong exception garantuee.


[%notitle]
=== Exception safety

In practice it is uncommon have a non-`noexcept` constructor, just as having a non-`noexcept` destructor, unless moving is equivalent to copying.
////
